version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - ./resumes.json:/app/resumes.json
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped 