version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/job_title_des.csv:/app/job_title_des.csv
    environment:
      - DATABASE_URL=sqlite:///./careeroos.db
      - SECRET_KEY=your-secret-key-here
      - UPLOAD_DIR=./uploads
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80 